[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "./start.sh"

[variables]
PORT = "5000"
CHROMA_DB_DIR = "/data/chroma"